################################################################################## 
# STAGE 0 - base environment with first set of runtime dependencies 
##################################################################################
ARG BUILD_TAG
ARG GIT_COMMIT

FROM centos:centos7 as libcppdb-lhdist-base-env

RUN yum -y --enablerepo=extras install epel-release && \
    yum -y install https://repo.ius.io/ius-release-el7.rpm && \
    yum clean all

##################################################################################
# STAGE 1 - build tools and libraries needed to build libcppdb
##################################################################################
FROM libcppdb-lhdist-base-env as libcppdb-lhdist-build-env

# for compiling and unit testing
RUN yum -y install \
        cmake3 \
        gcc \
        gcc-c++ \
        gtest-devel \
        make \
        rpm-build && \
    yum clean all

# for building an rpm package
RUN yum -y install rpm-devel rpmlint bash coreutils diffutils patch rpmdevtools && \
    yum -y clean all

RUN yum -y install wget bzip2 && \
    yum -y clean all
# wget
RUN yum -y update ca-certificates

##################################################################################
# STAGE 2 - built and packaged libcppdb
##################################################################################
FROM libcppdb-lhdist-build-env as libcppdb-lhdist-build

RUN mkdir -p /libcppdb-lhdist

ADD ./modules/lhscriptutil/scripts/rpmdev-setuptree-at.sh /libcppdb-lhdist
ADD ./dist/libcppdb-lhdist.spec /libcppdb-lhdist

RUN cd /libcppdb-lhdist && \
    mkdir build && \
    ./rpmdev-setuptree-at.sh ./build && \
    rpmbuild --define "_topdir ${PWD}/build"  -ba ./libcppdb-lhdist.spec && \
    mkdir -p /lhdist && \
    find ./build/RPMS/ | grep "\.rpm" | xargs -I{} cp -f -u {} /lhdist

ENV BUILD_TAG=${BUILD_TAG}
LABEL build_tag="${BUILD_TAG}"
ENV GIT_COMMIT=${GIT_COMMIT}
LABEL git_commit="${GIT_COMMIT}"

##################################################################################
# STAGE 3 - test /lhdist
##################################################################################
FROM libcppdb-lhdist-build-env as libcppdb-lhdist-check

ADD ./modules/lhscriptutil/scripts/refreshOrSetupLHDistYumRepo.sh /refreshOrSetupLHDistYumRepo.sh
RUN /refreshOrSetupLHDistYumRepo.sh
RUN yum -y repo-pkgs lhdistrepo install && \
    yum clean all

##################################################################################
# STAGE 4 - package in /lhdist
##################################################################################
FROM libcppdb-lhdist-base-env as libcppdb-lhdist-dist

COPY --from=libcppdb-lhdist-build /lhdist /lhdist